name: Build and Push Jotta-CLI
on:
  schedule:
    - cron: '0 0 * * 0' # Weekly auto-update
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/jotta-cli:latest .
          docker push ghcr.io/${{ github.repository_owner }}/jotta-cli:latest
